"""initial base

Revision ID: ae5dff3862b6
Revises: 
Create Date: 2023-11-27 12:57:03.338796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5dff3862b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newslinks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dt', sa.TIMESTAMP(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rss_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rss', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rss_sources')
    op.drop_table('newslinks')
    # ### end Alembic commands ###
