"""description added to rss table

Revision ID: 3a7b7f469879
Revises: ae5dff3862b6
Create Date: 2023-11-27 14:56:04.218481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7b7f469879'
down_revision: Union[str, None] = 'ae5dff3862b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rss_sources', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rss_sources', 'description')
    # ### end Alembic commands ###
